### ISSUE TITLE
Default "display:block" causes rendering issues

### ISSUE THREAD

**Issue by corysmc** [jagreehal/st-cc#4]
In the latest version of stencil and ionic, if I create a new page component using st-cc, I always have to remove the default "display:block" from the scss file for it to render.

Perhaps it's only an ionic issue, but thought I'd share.

Thanks for the great work! Saves tons of time!

**Comment by jagreehal** [comment]
Removed display:block. I'm thinking of allowing the user to use their own templates should they prefer to do so. What do you think?
